version: "3"

services:

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: ["sh", "-c", "sleep 20 && docker-entrypoint.sh postgres"]

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    command: ["sh", "-c", "sleep 30 && python manage.py runserver 0.0.0.0:8000"]

volumes:
  pgdata:
