version: "3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 81:81
    depends_on:
      - web
    restart: "on-failure"


  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    expose:
      - 8001
    depends_on:
      - db
  

volumes:
  pgdata:
